[custom]

;acl4SSR规则、自用

;设置规则标志位
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=DIRECT,[]GEOSITE,category-games
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🚀 节点选择,[]GEOSITE,!CN
ruleset=🚀 节点选择,[]GEOIP,!CN,no-resolve
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=DIRECT,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://cp.cloudflare.com`180,,30
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|TW|Taiwan)`http://cp.cloudflare.com`180,,30
custom_proxy_group=🇸🇬 新加坡节点`url-test`(坡|SG|Singapore)`http://cp.cloudflare.com`180,,30
custom_proxy_group=🇯🇵 日本节点`url-test`(日|JP|Japan)`http://cp.cloudflare.com`180,,30
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
